### ISSUE TITLE
Injecting custom packages returns System.NullReferenceException

### ISSUE THREAD

**Issue by LeaPhant** [HoLLy-HaCKeR/osu-HOPE#6] opened 2017-09-01 11:42 UTC
After fiddling around with the plugin interface I got to the following code:

```C#
using System.Collections.Generic;
using HOPEless.Bancho;
using HOPEless.Bancho.Objects;
using osu_HOPE.Plugin;

namespace Hope.Plugin.UserStatusRequest
{
    public class UserStatusRequestPlugin : IHopePlugin
    {
        public PluginMetadata GetMetadata()
        {
            return new PluginMetadata
            {
                Name = "UserStatusRequest",
                Author = "Node",
                ShortDescription = "requests user info without manually opening the users list",
                Version = "1.0"
            };
        }

        public void Load() { }

        public void OnBanchoRequest(ref List<BanchoPacket> plist) { }

        public void OnBanchoResponse(ref List<BanchoPacket> plist) {
            var requestedUsers = new BanchoIntList();
            requestedUsers.Value.Add(754565); // hard-coded value for testing
            plist.Add(
                new BanchoPacket(PacketType.ClientUserStatsRequest, requestedUsers)
            );
        }
    }
}
```

I used custom channel injection from Example2 as reference, however when trying to run it I get the following error: 

```
Exception occured in plugin UserStatusRequest OnBanchoRequest: System.NullReferenceException: Object reference not set to an instance of an object.
   on Hope.Plugin.UserStatusRequest.UserStatusRequestPlugin.OnBanchoResponse(List`1& plist)
   on osu_HOPE.Program.<OnResponse>d__4.MoveNext() in C:\Users\Node\Documents\osu-HOPE\osu!HOPE\Program.cs:Line 124.
```

**Comment by holly-hacker** [comment] 2017-09-01 14:20
Seems like the Value variable in BanchoIntList does not get initialized. adding `requestedUsers.Value = new List<int>()` should make it work for you. You can see the code for BanchoIntList [here](https://github.com/HoLLy-HaCKeR/HOPEless/blob/48ec35957bda2277a085fe6835f4e9d35fbd9c72/HOPEless/Bancho/Objects/SimpleTypes.cs#L13) if you want to. 

I'll have to finish HoLLy-HaCKeR/HOPEless#2 to make it more intuitive, so I won't close this yet.

**Comment by LeaPhant** [comment] 2017-09-01 14:56
Okay, it runs without errors now, but I immediately get disconnected from bancho when I run it. Is there any reason why this is happening?

**Comment by holly-hacker** [comment] 2017-09-01 16:43
Does it not reconnect right after? For me, it would initially disconnect on login but then connect successfully. This is a bug I don't really have the motivation for to fix it, but it shouldn't really give any problems since osu! will successfully reconnect right after.

**Comment by LeaPhant** [comment] 2017-09-01 22:09
No, it doesn't reconnect.

**Comment by holly-hacker** [comment] 2017-09-02 09:22
I don't know what it is then, sorry.

**Comment by holly-hacker** [comment] 2017-09-02 11:43
Just to make sure, what happens if you run the osu!HOPE with none or the default plugins? If that works, the issue is most likely that you write invalid data to the packet's body.

**Comment by LeaPhant** [comment] 2017-09-02 13:13
Yeah, it's the plugin, but I don't know what's invalid since I'm basically just doing what's in LoggerPlugin but in reverse.

```C#
var requestedUsers = new BanchoIntList();
requestedUsers.Populate(packet.Data);
requestedUsers.Value.ForEach(Console.WriteLine);
Console.WriteLine($"Asking user info on {requestedUsers.Value.Count} user{(requestedUsers.Value.Count==1 ? "" : "s")}");
```

to

```C#
var requestedUsers = new BanchoIntList();
requestedUsers.Value = new List<int>();
requestedUsers.Value.Add(754565); // hard-coded value for testing
plist.Add(
    new BanchoPacket(PacketType.ClientUserStatsRequest, requestedUsers)
);
```

Or am I missing something?

**Comment by holly-hacker** [comment] 2017-09-02 23:28
I think I see the problem. If you look at your original code, you're adding a Client* packet in the OnBanchoResponse method. OnBanchoResponse contains the packets that bancho sends back to the client, which is prefixed with Server*. Move your code to the OnBanchoRequest method (contains packets sent to bancho) and it sohuld work.

The client is most likely choking because it got a packet it doesn't recognize.

**Comment by holly-hacker** [comment] 2017-09-04 13:33
Any updates? I'll close this issue if there are no other problems.

EDIT: Last commit updated the HOPEless submodule, your problems should be resolved with that so make sure to update.

**Closed as completed** 2017-12-27 13:45 UTC
